package apicc.model.entity;

public enum EReportType {
    BREAKING_RULES,HARASSMENT,HATE,SHARING_PERSONAL_INFO,IMPERSONATION,COPYRIGHT_VIOLATION,

    TRADEMARK_VIOLATION,SPAM,SELF_HARM_OR_SUICIDE,OTHER;
}
